### ISSUE TITLE
LR - memory points, pip

### ISSUE THREAD

**Issue by evromalarkey** [evromalarkey/ACR-Mod#35]
- [x] pip zrcadka / asi potřeba dodělat selekce, memory pointy už tam jsou
- [x] nejak fixnout destroy textury // srat na to v tomhle releasu
- [x] v 1st pohledu nejde animace otaceni rukou  (volant se toci) // nope, nic takoveho
- [x] animace (cargo poses)
- [x] FFV
- [x] memory points, physx
- [x] zaslehy, zbraně
- [x] Slingloading
- [x] - tachometr apod. je opačně
- [x] - lesni special nema lesni korbu (snad fixed) // not fixed
- [x] - LR s plachtou a ambulance potřebujou jinou animaci řidiče
- [x] - typek v zadnim FFV je nezabitelnej

**Comment by Kllrt** [comment]
jasan

**Comment by evromalarkey** [comment]
http://youtu.be/EYmJ2R309YA

**Comment by evromalarkey** [comment]
- [ ] - tachometr apod. je opačně
- [ ] - lesni special nema lesni korbu

**Comment by evromalarkey** [comment]
@Kllrt přenechávám tobě

**Comment by Kllrt** [comment]
podivam se na to

**Comment by evromalarkey** [comment]
liar - animace (cargo poses)

**Comment by evromalarkey** [comment]
[ ] - LR s plachtou a ambulance potřebujou jinou animaci řidiče

**Comment by Kllrt** [comment]
Pice...zrcadka nejdou, v zadu manik s FFV nejde trefit, je neprustrelnej (asi vim cim to je ale nemam cas :D) a ty hidden selekce mi taky furt nejdou.
