### ISSUE TITLE
Chtelo by to rozdelit Pruzkumniky a normalni vojaky do zvlastnich zalozek

### ISSUE THREAD

**Issue by Bakarda** [evromalarkey/ACR-Mod#42]
Pruzkumnici maj bejt specialni jednotky a normalni armada maji byt normalni vojaci, ted se to dost plete

**Comment by Kllrt** [comment]
baki pls

**Comment by evromalarkey** [comment]
průzkumníci dřív měli vlastní vehicle class, dalo se to do jedné kategorie aby to bylo přehlednější.. bezkat před tim jménem maj "průzkumník -"
