### ISSUE TITLE
MAAWS s optikou

### ISSUE THREAD

**Issue by ZikiCZ** [evromalarkey/ACR-Mod#44]
(používáme ACR_A3 - CUP Weapons, addony pack (real armor mod nepoužíváme): http://withsix.com/p/Arma-3/collections/gJ5WzecQaUGt0DJiAN30Dg/C-S-E-C-addony-na-server)
1. Balistika raket neodpovídá záměrným křížum v optice.
2. Nefunguje dálkoměr optiky, zobrazeny jsou asi čtyři pomlčky, které jsou vidět poté i mimo optiku, když má hráč raketomet v ruce.

Chtělo by to přidat nastavitelný náměr pro kovová mířidla. 
(Teď se v kombinaci s prvním bodem střílí jen s odhadem.)

**Comment by evromalarkey** [comment]
na optikus se podívám, ale zbytek prosím hlásit na cup issue tracker, to už je chyba v cup weapons http://bugs.cup-arma3.org/
