### ISSUE TITLE
Chybí LRTV u ACR_A3 - CUP Weapons

### ISSUE THREAD

**Issue by ZikiCZ** [evromalarkey/ACR-Mod#45]
Po inicializaci mise nebo v arsenálu vyběhne hláška tohoto chybějícího zařízení.
(addon pack (real armor mod nepoužíváme): http://withsix.com/p/Arma-3/collections/gJ5WzecQaUGt0DJiAN30Dg/C-S-E-C-addony-na-server)

**Comment by evromalarkey** [comment]
můžu screenshot te hlášky kdyžtak?

**Comment by ZikiCZ** [comment]
Pokusim se jí odchytit a potom poslat.
Tady je zatim další hláška:
![2016-02-01_00001](https://cloud.githubusercontent.com/assets/16736083/12725934/54e30b06-c915-11e5-9139-e848e107cec8.jpg)

A ještě drobnost: pozorovatel (B_ACR_A3_Spotter) má na zbrani ACOG a ve hejkalu zbytečně ještě RCO.

**Comment by ZikiCZ** [comment]
![2016-02-09_00001](https://cloud.githubusercontent.com/assets/16736083/12929447/07779ba2-cf73-11e5-9676-b8baa457db7d.jpg)

Tady je ta chyba.
Jinak trasírky do vz. 58 taky moc nefungují.

**Comment by ZikiCZ** [comment]
Tak jsme z jednoho vymlátili to, že používal plný CUP Weapons. Nicméně ta chyba s M24 je i v sp/editoru, čili tam u očesané verze pro AČR něco skutečně chybí.
co se týče trasírek do kosy, tak chyba je i plném CUPu, takže to pak někdy napíšu na ten CUP.

**Comment by evromalarkey** [comment]
na všechny chyby zkusim mrknout o víkendu
